title:              Giua App - Scarica ora
description:        L'app Android dell'Istituto d'Istruzione Superiore "Michele Giua" per Studenti e Genitori
baseurl:            ""
url:                "https://giua-app.github.io"

# Build settings
markdown:           kramdown
#paginate:           5
#paginate_path:      "/posts/page:num/"
plugins:
  #- jekyll-feed
  #- jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
