title:              Giua App
description:        L'app dell'Istituto d'Istruzione Superiore "Michele Giua"
baseurl:            ""
url:                "https://giua-app.github.io"
markdown: kramdown

# Build settings
markdown:           kramdown
#paginate:           5
#paginate_path:      "/posts/page:num/"
plugins:
  #- jekyll-feed
  #- jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
